### ISSUE TITLE
java.lang.OutOfMemoryError (not sure if lithium's fault)

### ISSUE THREAD

**Issue by supersaiyansubtlety** [jellysquid3/Lithium#128]
### Reproduction Steps
Seems to happen after a while of exploring new chunks. 
### Crash Report File
This is the crash report that mentions lithium:
[crash-2020-08-29_18.46.03-server.txt](https://pastebin.com/L3NqSwCC)

### Additional Information
Note that I've also been experiencing similar crashes that don't mention lithium, here's a report from one of those:
[crash-2020-08-29_18.34.00-server.txt](https://pastebin.com/4Dtz3Y2n)

**Comment by FlashyReese** [comment]
You need to allocate more memory to JVM.

**Comment by amnotbananaama** [comment]
This is not caused by Lithium. Especially with the amount of mods/datapacks you have, 1GB of memory isn’t sufficient. 

If you aren’t sure how to allocate more memory, join Jelly’s discord where we can walk you through the process without spamming the tracker. If you don’t have more memory to allocate than 1 GB, I would suggest reducing the amount of mods/datapacks you are running, look into upgrading your hardware, or join Jelly’s discord where we can suggest low-memory JVM options

**Comment by supersaiyansubtlety** [comment]
This is my current `run-server.bat`:
```
java -Xmx1G -jar fabric-server-launch.jar nogui
```
What amount of memory is recommended?

**Comment by supersaiyansubtlety** [comment]
I'll just try 4GB, thanks for your help.
