### ISSUE TITLE
Invisible Chests when unloading and reloading chunks - 0.5.5-SNAPSHOT

### ISSUE THREAD

**Issue by FlashyReese** [jellysquid3/Lithium#137]
### Expected Behavior
https://streamable.com/yfgmi7

### Actual Behavior
https://streamable.com/5s41yl

### Reproduction Steps
Summary:
Minecraft 1.16.3 + [Lithium 0.5.5-SNAPSHOT](https://discordapp.com/channels/602796788608401408/648967810139029505/753853455910830133) + [My fork of sodium](https://github.com/FlashyReese/sodium-fabric/releases/tag/mc1.16.2-0.1.0-stable) = Occurs
Minecraft 1.16.3 + Lithium 0.5.4(Removed version lock) + [My fork of sodium](https://github.com/FlashyReese/sodium-fabric/releases/tag/mc1.16.2-0.1.0-stable) = Doesn't occur

Note:
~~I also tried disabling all the features via Lithium's configuration file, it still occurs.~~
I can also confirm this occurs on the internal server.

Edit: Disabling `mixin.world.block_entity_ticking` fixes the issue

After some discussion with [Lucy](https://github.com/Lucy-t) and [Kichura](https://github.com/Kichura) at [#lithium](https://discordapp.com/channels/602796788608401408/648967810139029505/754647409396547715) on discord we figured we should open this issue since recent changes made to Lithium ~~will~~ might break with Sodium in the future.

**Comment by 2No2Name** [comment]
Can you still reproduce this with the latest commit?

**Comment by FlashyReese** [comment]
Yes, I can still reproduce this with https://github.com/jellysquid3/lithium-fabric/commit/9f11468569bbd4f1cc8c182d77e329d45f5bd648 .

**Comment by 2No2Name** [comment]
Thank you. I found another problem with the implementation and pushed another fix. Can you test again?

**Comment by FlashyReese** [comment]
Also reproducible with https://github.com/jellysquid3/lithium-fabric/commit/15487bc72fc97b07a58065bff7eebf609bfd8310

**Comment by 2No2Name** [comment]
Another try to fix it is here: https://github.com/2No2Name/lithium-fabric/tree/1.16.x/pull/fixBlockEntityList

**Comment by FlashyReese** [comment]
Yes that has fixed the issue.

**Comment by Kichura** [comment]
![image](https://user-images.githubusercontent.com/68134602/96256037-35721480-0fb8-11eb-9aaa-c973c7357d46.png)
Wanted to make a follow-up about the lithium update, The issue is still present on my end via 1.15.2 protocol with 0.5.6 lithium (Even with config set to false for the time being).

However i can't really confirm if this issue applies to the API itself or lithium alone + Something else i noticed was that blocks don't register to client-side screen properly when changing blocks from another client via 3rd-party fabric servers that use older lithium.
