### ISSUE TITLE
Remove (or relax) Lithium's version requirements 

### ISSUE THREAD

**Issue by harl** [jellysquid3/Lithium#139]
The underlying issue for this request is that some of Minecraft's versioning can only barely be interpreted as a significant indicator for compatibility. For example, the changes made with Minecraft 1.16.3 are rather specific and probably don't affect most mods, plugins and even players in general. Still, as long as a mod explicitly asks for a specific version of the game, Minecraft simply doesn't go through with the loading procedures and then "crashes" instead.

There are common alternatives to this behaviour.
The game could include some optional way to try and load mods/plugins anyway even when their version requirements aren't met, and inform the user about it so they can make an informed decision, see if they still work or update their files respectively.
The game could just (optionally?) ignore any related mods/plugins, dependants & dependencies and continue to start up without them instead of crashing, and inform the user about it so they can update their files or enable the aforementioned option to load them anyway.

The mod could be compiled without a strict version requirement (rather a version recommendation if the game supports it) or it could just require a specific minimum version, and inform the user about it either way, so they know the mod was really tuned to a specific game version but it may or may not as well load with a newer version (then maybe go on to automatically check for an updated file, although that may produce lots of unnecessary update checks between game updates and mod updates).

**Comment by akiraveliara** [comment]
1.16.3 is a fair point on that note, generally lithium is very delicate with version changes though and needs at least some adaption

**Comment by jellysquid3** [comment]
We try to provide very strict guarantees that Lithium will not change game behavior and will be imperceptible to the player. As has been the case with a number of recent updates, Mojang has changed behaviors in subtle ways which allow Lithium to break this guarantee when ran on the wrong version, or straight up crash in cryptic ways that users don't understand.

There have been almost zero updates in the last ~3 months which haven't required some modifications to Lithium in order to fix up compatibility or behavior parity, and as I've discussed this issue with the team here before, we're pretty much all on board that we want to continue providing a strict version requirement. The issue with Minecraft 1.16.3 is exceptionally rare and we don't usually see such micro-updates from Mojang.

As for your suggestions to error reporting or dependency management: We don't have much control over it. What you're looking for is a dedicated mod manager, or at least some improvements to [Fabric Loader](https://github.com/fabricmc/fabric-loader) itself.
