### ISSUE TITLE
Incompatibility with the mod Creeper Spores

### ISSUE THREAD

**Issue by Leeo97one** [jellysquid3/Lithium#149]
### Expected Behavior
The Creeper Spores status effect should be given to any entity caught in a creeper explosion.
See: https://www.curseforge.com/minecraft/mc-mods/creeper-spores

### Actual Behavior
No status effect is given.

### Reproduction Steps
1. Load the mods Lithium and Creeper Spore
2. In-game, spawn a creeper
3. Let the creeper explode next to you

**Comment by 2No2Name** [comment]
This is probably caused by the explosion optimization. Try adding the line
`mixin.world.explosions=false`
to the lithium.properties file to work around it

**Comment by Leeo97one** [comment]
Thanks for the workaround, It Works:tm:.

**Comment by jellysquid3** [comment]
I don't think there's anything we can do to fix this issue. While this incompatibility is unfortunate, strictly speaking there isn't really  bug in either Lithium or Creeper Spores... they just can't patch the exact same code. For the time being however, Creeper Spores can specify in their mod manifest that Lithium should disable its conflicting patches using the following attribute:

```json
"custom": {
  "lithium:options": {
    "mixin.world.explosions": false
  }
}
```

In the future, perhaps Fabric API could provide events for when an entity is damaged by a explosion so that mods like this can add custom behavior without needing to patch game code, in effect enabling better compatibility.
