### ISSUE TITLE
[non-vanilla behavior]when "use_swept_collision_search" true, mechine in the following will have a chance to shoot tnt forward

### ISSUE THREAD

**Issue by Harveykang** [jellysquid3/Lithium#16]
lithium-mc1.15.2-fabric-0.3.2
maybe happens on mc1.16mod too?
How to reproduce: 
![image](https://user-images.githubusercontent.com/46108547/75106723-561ce100-565a-11ea-8c37-cfa249aec9c7.png)
![image](https://user-images.githubusercontent.com/46108547/75106725-59b06800-565a-11ea-858f-38c80970a246.png)
![image](https://user-images.githubusercontent.com/46108547/75106727-5d43ef00-565a-11ea-82f9-898ec77038b4.png)
trigger and retrack the sticky piston, notice the tnt has chance to be shoot forward
![A} %)3P2G63KV82C(LM3O9D](https://user-images.githubusercontent.com/46108547/75106819-5ec1e700-565b-11ea-9e1d-59fe3eb4c279.png)
turn "use_swept_collision_search" false, the game runs as normally as vanilla, all tnt falls down

**Comment by niyuyeye** [comment]
你是怎么关闭这个选项的

**Comment by Harveykang** [comment]
看它的wiki：https://github.com/jellysquid3/Lithium/wiki/Configuration-File

**Comment by niyuyeye** [comment]
谢谢，找到了

**Comment by rmkwulf1993** [comment]
I am having the same issue on my 1.15.2 server, using the same tnt module above without lithium the tnt behaves as intended

**Comment by jellysquid3** [comment]
I'm having trouble reproducing this issue as described despite the provided instructions. If someone could send over a copy of their world with an affected machine, it would go a long way towards working out what is happening here.

**Comment by rmkwulf1993** [comment]
Hey Jelly, I will send you my world download when I get home, I also
noticed phosphor renders it client side the same way it appears to shoot
forward even if its falling down (without lithium). With lithium it
actually shoots the tnt forward instead of down. Ill send some more info as
well where possible.

On an unrelated note lithium has made my server run buttery smooth
sometimes even 20mspt better.

**Comment by jellysquid3** [comment]
I've been looking into this issue for the past few days, and I think that the best course of action is to remove these sweeping box patches all together as they have correctness issues when handling over-sized block shapes. In most situations, vanilla's more naive approach will outperform Lithium by a fair margin.

Thanks everyone for helping to narrow down the issue here. The patches have been removed with ce8ed9a and have been backported to Minecraft 1.15.
