### ISSUE TITLE
Crashes on 1.16.4 with only Lithium and Fabric API for 1.16.4

### ISSUE THREAD

**Issue by aestellic** [jellysquid3/Lithium#162]
### Reproduction Steps
Provide information on how to reproduce this game crash. This step is critical for ensuring that your crash can be debugged by other developers. You can either fill in the example below or do something else -- just make sure your instructions are minimal and clear. If applicable, provide a Minecraft save containing a minimal example on how to reproduce this crash as a compressed ZIP file.

1. Put Lithium and Fabric API 1.16.4 in mods folder.
2. Launch game
3. The game crashes

### Crash Report File
(https://gist.github.com/MudkipBanana/5b511e6123ea13f7e393f79f4a067ac1)

### Additional Information
None

**Comment by silversquirl** [comment]
Lithium does not yet support 1.16.4

**Comment by ghost** [comment]
Lithium does support 1.16.4, make sure you download the appropriate branch from the actions tab.

**Comment by ghost** [comment]
> Lithium does support 1.16.4, make sure you download the appropriate branch from the actions tab.

First I would like to say I am not the official developer and I have not much java experience.
I like to think that version should not be used in non-testing environments,
because if it was confirmed to be stable then it would be released on curse forge.
I haven't noticed bugs iirc,
you can use it,
people say it is stable but I can't say that for sure,
beware issues,
use it at your own risk.

**Comment by ghost** [comment]
I get that, it isn't stable, but I believe that testing snapshots do help the developers; kind of similar to playtesting. Making sure it is compatible with other mods. I'm no expert at Java, I just look for compatibility.
