### ISSUE TITLE
Game will not start as of latest commit (732196f)

### ISSUE THREAD

**Issue by NoComment1105** [jellysquid3/Lithium#174]
### Reproduction Steps
I build lithium from the source on github.com and compiled it using java 14

1. Download and compile lithium from commit 732196f14ac12b2b2ba3ca6426e3299686c238a5
2. Start up game
3. The game crashes

### Crash Report File
[crash-2020-12-17_18.11.17-server.txt](https://github.com/jellysquid3/lithium-fabric/files/5711595/crash-2020-12-17_18.11.17-server.txt)

### Additional Information
I used openjdk 14 to build this

**Comment by ReperakDev** [comment]
If you are able to, could you provide more information such as:
* Gradle command used to build
* Lithium config (Found in .minecraft/config/)
If it's not important, a common issue is a messed up Lithium config, you can try removing it to see if that fixes it.

**Comment by Ampflower** [comment]
Considering the crash has `Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Variable modifier method `**`createShortHashSet(B)B`**` in `**`lithium.mixins.json:chunk.section_update_tracking.ChunkHolderMixin`**` failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap mixins.lithium.refmap.json`, I suspect that dd1f2fc416f8aa5b32ed2d593ab6fb13c34b8b0e, the commit that introduced this injection, doesn't account for other mods as well as it should.

Update; it appears that this patch does not work outside of a development environment, see [#mod-support](https://canary.discord.com/channels/602796788608401408/602805020861267968/789353462407233566).

**Comment by NoComment1105** [comment]
gradlew build -Dorg.gradle.java.home=/"C:\Program Files\AdoptOpenJDK\jdk-14.0.2.12-hotspot" (i assume you mean this)
it wouldn't let me add lithinum properties

**Comment by ReperakDev** [comment]
That looks like a successful build, however since Minecraft and Fabric Mods are compiled against Java 8, Java 14 can cause some issues. You could give compiling against Java 8 a try.

**Comment by NoComment1105** [comment]
This is odd though. I used to be fine when compiling using java 14, only recently it was giving me the issue of me have java 8 jre all of a sudden so now I need to use this: gradlew build -Dorg.gradle.java.home=/"C:\Program Files\AdoptOpenJDK\jdk-14.0.2.12-hotspot" and I don't want to go back to java 8

**Comment by ReperakDev** [comment]
Don't worry, Java is compatible with jars compiled with previous versions. You don't have to switch back to Java 8 as Java 8 jars run fine on Java 14.

**Comment by NoComment1105** [comment]
okay, thanks for the help. atm I'm just using the stable release of lithium, ill wait a bit for changes. :)

**Comment by Heitzenberg** [comment]
I can confirm that this is an issue when using Java 8 as well.

**Comment by 2No2Name** [comment]
https://github.com/jellysquid3/lithium-fabric/commit/a818d2a259f7a73f7caa35652b2ae63eab5bda53 should fix that

**Comment by NoComment1105** [comment]
a818d2a does fix this issue, thank you for your help, I will close this issue now, thanks

**Comment by ParzivalPanda** [comment]
I've had the saem issue but for some reason, in the latest version from November 10th, I don't have the file "section_update_tracking" to edit in the first place. Not sure if this is the right place to put this, if not, please just let me know. Thanks!
