### ISSUE TITLE
Option system does not disable mixins when requirements are not met

### ISSUE THREAD

**Issue by AngelofWoe** [jellysquid3/Lithium#246]
After updating to 0.7.2 from 0.7.1, having mixin.ai=false in lithium.properties results in server crashing on every attempt to start.

Please find crash-reports and lithium-properties in zip archive attached.

Side-note: We've been disabling mixin.ai due to lots of issues with villagers not picking up professions when it isn't disabled. Disabling mixin.ai on 0.7.1 was letting villagers pick up professions, and now on 0.7.2 without this option disabled the villagers are back to not picking up professions again, at least not without significant delays.

[crash-2021-06-19_07.11.47-server.zip](https://github.com/CaffeineMC/lithium-fabric/files/6680772/crash-2021-06-19_07.11.47-server.zip)
(Server times are in UTC)

**Comment by 2No2Name** [comment]
mixin.block.hopper depends on ai.nearby_entity_tracking being enabled. The option system should have automatically turned off mixin.block.hopper because ai is disabled, which is a bug.
So for now, you should either enable mixin.ai.nearby_entity_tracking or disable mixin.block.hopper.

Can you open a separate issue for the villagers behaving differently from vanilla? We are interested in fixing that as well

**Comment by 2No2Name** [comment]
This should fix it https://github.com/CaffeineMC/lithium-fabric/commit/26ebde00d490db17137fc79705ff0640fc8fe349
If you have a more detailed description for the villager issue, please open another issue

**Comment by AngelofWoe** [comment]
> This should fix it [26ebde0](https://github.com/CaffeineMC/lithium-fabric/commit/26ebde00d490db17137fc79705ff0640fc8fe349)
> If you have a more detailed description for the villager issue, please open another issue

Thank you, I'll try to gather more info on the villager issue.

The mods on the server that are more experienced with villager AI say they'll try to do a writeup and recording tonight when the server isn't busy.
