### ISSUE TITLE
Exception while ticking 0.4.6 - MC Server 1.15.2

### ISSUE THREAD

**Issue by PanoptesDreams** [jellysquid3/Lithium#26]
[latest.log](https://github.com/jellysquid3/lithium-fabric/files/4424667/latest.log)

[crash-2020-04-03_14.46.34-server.txt](https://github.com/jellysquid3/lithium-fabric/files/4424670/crash-2020-04-03_14.46.34-server.txt)

**Comment by jellysquid3** [comment]
Your crash appears to be caused by the Curses mod, which is injecting code into the ItemStack class [here](https://github.com/HyperPigeon/Curses-/blob/3a90cbb68b93bd019c99eb7ae2fb6f7d6283f353/src/main/java/net/hyper_pigeon/curses/mixin/ItemStackMixin.java#L104). It looks like the author expected `player` to be null, but is performing the check after it has already tried to operate on it, leading to the crash. 

Please open an issue with the other mod's developers.
