### ISSUE TITLE
[1.19.2] Several crashes from several mixins constant

### ISSUE THREAD

**Issue by itsdinkd** [jellysquid3/Lithium#464]
Before i add all the required details, I wanted to make sure its fine that I post what i'd like to post....

In my modpack, Another Quality Modpack 2, for 1.19.2, my official servers have been consistently crashing 6-10 times a day, all watchdog crashes from lithium mixins. There is no reproduction steps, it just happens randomly. 

After disabling the following mixins, ( I disabled one at a time to see if it would eliminate that consistent crash for the specified mixin in the crash log) the crash stopped occurring 

```
mixin.world.chunk_access=false
mixin.world.block_entity_ticking=false
mixin.world.chunk_inline_block_access=false
mixin.ai.pathing=false
mixin.alloc.chunk_ticking=false
```

The above mixins are the sum of all that work. 

Most recent one was mixin.alloc.chunk_ticking which happened 4 times in the last 30 hours. After disabling that mixin, no more crash.

---

I have tons, and tons of crash reports going back 30 days each crash report in relation to each mixin (shoutouts to MixinTrace mod). Should I upload these? What would be the best way to deliver these logs to you so you can be aware of these issues?

**Comment by itsdinkd** [comment]
https://gist.github.com/itsdinkd/0d4b629fe091ffa535c969c13a238fee here is one for
https://gist.github.com/itsdinkd/b00ef8c271803d88d8ba4dd3ed38e206
world.chunk_access


consistently happening when I re-enabled.

**Comment by 2No2Name** [comment]
It is not plausible that the watchdog crashes are caused by lithium just because lithium shows up in the stack traces.

**Comment by itsdinkd** [comment]
> 

Regardless of what you believe is plausible just by **assuming**, I disabled these mixins and the crashes magically stopped, going from 8x crashes a day spread out through these mixins to.... 0.

Super glad that this was your response after nearly 2 months.

**Comment by 2No2Name** [comment]
Watchdog crashes with a huge number of mods are almost impossible to debug. Lithium is very likely to show up in stacktraces of watchdog crashes, because lithium replaces many functions of the tick loop and the chunk access. Chunk accesses are often included in watchdog stacktraces because loading chunks is a slow operation.

It is very helpful that you provided a list of lithium's features which can be disabled to avoid the issues with the given set of mods. This hints at a mod compatibility issue being the source of your watchdog crashes (using lithium alone does not cause those crashes, as we would be flooded with reports otherwise). Investigating potential mod compatibility issues is a lot of work with such a long list of mods.

What is very interesting is that both of your watchdog crashes occur during the processing of network packets. This might hint at some kind of logic error, but could also be a coincidence. If you want to post the examples for the other watchdog crashes, I will take a look at them.

I suggest that you keep the mixins that you identified disabled, as it is not likely that I will come up with another solution that works for you. If you want to spend a lot of time on finding the root cause, you can re-enable those mixins and uninstall half of your mods at a time, to narrow down which combination of mods leads to the watchdog crashes.
