### ISSUE TITLE
1.12.2 backport possible?

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Lithium#48]
I'm not asking anyone to do it necessarily, but I am curious if it is possible. I'm a software engineer and would love to give a crack at a backport, but would love to know about any potential problems

**Comment by AMereBagatelle** [comment]
It may be possible for this specific project in the future, but not right now.
Fabric Loader, while it is version-independent, does not have mappings nor any dev-tools for 1.12.2.
Forge might be a option, if you are really dedicated, but it would be a lot of work.
Maybe it could be possible for Liteloader on the client, but again it would be a lot of work because of the differences between versions, with many of Lithium's patches only applying to newer versions.

**Comment by ghost** [comment]
Thanks for the fast response! Some interesting things to think about there!
