### ISSUE TITLE
lithium could run with optifine(optifabric) if you add a config file

### ISSUE THREAD

**Issue by RottenSea** [jellysquid3/Lithium#491]
if you want to run lithium with optifabric
you only need to download the json file (fabric_loader_dependencies.json)
then add it to your version/[version name]/config folder
i just tested 1.16.5 and it was worked

**Comment by astridellensdottir** [comment]
the reason for incompatibility is because optifine touches so many of the game’s internals, and does so behind closed source, it would be hard to be sure that the combination wasn’t altering vanilla behavior. 

additionally, just because it starts and you don’t have any warnings in the log yet doesn’t mean it actually works.

**Comment by RottenSea** [comment]
> the reason for incompatibility is because optifine touches so many of the game’s internals, and does so behind closed source, it would be hard to be sure that the combination wasn’t altering vanilla behavior.
> 
> additionally, just because it starts and you don’t have any warnings in the log yet doesn’t mean it actually works.

I guess... it's not that lithium can't be run with optifabric...
They just don't have permission to load
![{D57921F6-1D24-4f2a-BDB7-517B77504F5E}](https://github.com/CaffeineMC/lithium-fabric/assets/86948417/03c172d1-4ad9-405d-95f0-e6553814744e)
