### ISSUE TITLE
Request: update to 1.20.4

### ISSUE THREAD

**Issue by ghost** [jellysquid3/Lithium#499]
Request: update to 1.20.4

**Comment by ghost** [comment]
It'll be updated once it's ready™️

**Comment by devjta** [comment]
Last change 4 days ago, which was the update to 1.20.4..

**Comment by ghost** [comment]
> ###
> [Dec 15, 2023](#issuecomment-1858031211)

But no jar file?

**Comment by jellysquid3** [comment]
We don't need people asking us to update our mods.

And there isn't any explanation required when there's a bit of delay. It's only been a few days.

Just be patient. We each have our own lives.

**Comment by ghost** [comment]
> We don't need people asking us to update our mods.
> 
> And there isn't any explanation required when there's a bit of delay. It's only been a few days.
> 
> Just be patient. We each have our own lives.

Thats the least nice respond i ever got on a github request.
I was just asking because i love to use the mod but now i know how the owners reply im gonna rethink my options.

**Comment by CamperSamu** [comment]
Never ask for ETAs, ever. (specially if you are not a donator for the project)
It's the most disrespectful thing you can do to a free and open source developer for a free and open source project.

This Twitter thread by the lead dev of Oh The Biomes You'll Go sums it up perfectly:
https://twitter.com/CorgiTaco/status/1735250675129581921

**Comment by theofficialgman** [comment]
> > We don't need people asking us to update our mods.
> > And there isn't any explanation required when there's a bit of delay. It's only been a few days.
> > Just be patient. We each have our own lives.
> 
> Thats the least nice respond i ever got on a github request. I was just asking because i love to use the mod but now i know how the owners reply im gonna rethink my options.

@jurohn Hi jurohn.
The response was brief, to the point, and non-argumentative. I don't see anything un-nice in the response. Constructive feedback is always appreciated.

However, the reality is that a developer is not obligated to give you a response at all. On top of that the developers here have made it crystal clear that under no circumstances should ETAs be asked for in GitHub issues (see the pinned issue https://github.com/CaffeineMC/lithium-fabric/issues/190).

Please make sure to read the pinned issues and issue templates before wasting everyone's time in the future at this repo and otherwise.
