### ISSUE TITLE
Lithium 0.13.0 explosion optimization incompatible with Carpet Mod

### ISSUE THREAD

**Issue by Heitzenberg** [jellysquid3/Lithium#543]
Here's the crash report: https://pastebin.com/c3VCVChz

Looks like a compatiblity issue with carpet mod maybe?

**Comment by 2No2Name** [comment]
https://github.com/gnembon/fabric-carpet/pull/1937

**Comment by 2No2Name** [comment]
Workaround: Manually disable lithium's optimization in the lithium.properties file in the config folder by adding the following line to it:
`mixin.world.explosions.cache_exposure=false`

This mod incompatibility should also be fixed by the above PR to carpet, but it is uncertain when it will be merged.

**Comment by 2No2Name** [comment]
https://github.com/CaffeineMC/lithium-fabric/issues/521

**Comment by schrummy14** [comment]
Workaround is working for me (mods are lithium, fabric-api, and carpet) on MC 1.21.1 with fabric-loader 0.16.0.

**Comment by ArduFish** [comment]
Can confirm

**Comment by PigsWorth** [comment]
> Workaround: Manually disable lithium's optimization in the lithium.properties file in the config folder by adding the following line to it:
> 
> `mixin.world.explosions.cache_exposure=false`
> 
> 
> 
> This mod incompatibility should also be fixed by the above PR to carpet, but it is uncertain when it will be merged.

What does disabling this do as far as optimization (ie. extent of impact on regular lithium performance)?
