### ISSUE TITLE
what does this mean (server side)?

### ISSUE THREAD

**Issue by VaporeonScripts** [jellysquid3/Lithium#586]
neoforge 1.21.1 .79, latest lithium version
os: arch linux (CachyOS)
> Lithium Cached BlockState Flags are disabled!

**Comment by 2No2Name** [comment]
Lithium generates information about each block state at startup and uses the information to speed up various parts of the game. But since this information is dependent on block tags, which can be changed by data packs, the optimization is incorrectly using the outdated block tag information. For this reason the optimization is disabled by default until this is fixed.

The affected setting is `mixin.util.block_tracking`

**Comment by VaporeonScripts** [comment]
so its normal to have it like that?

**Comment by 2No2Name** [comment]
Yes, currently everyone has that

**Comment by VaporeonScripts** [comment]
aight,ty

**Comment by VaporeonScripts** [comment]
is it still normal ? since i still get it
