### ISSUE TITLE
1.21 backport

### ISSUE THREAD

**Issue by pivoland** [jellysquid3/Lithium#596]
Hi! Could you please backport the new version of lithium to 1.21? I was hoping that this would be possible just by changing fabric.mod.json but it breaks the game. For some reason, I can't update to 1.21.1. At the same time, mods like Carpet TIS or Async don't work with the old lithium. 

I'm sorry if I'm asking for something too much.

**Comment by rilakuma123** [comment]
Until 2No2Name decides what to do here, you can do a dependency override: https://wiki.fabricmc.net/tutorial:dependency_overrides

I recommend switching to 1.21.1 and then creating a dep override for any 1.21 dependent mods

**Comment by jellysquid3** [comment]
Nearly every mod-- if not all of them-- which are compatible with Minecraft 1.21 will also be compatible with Minecraft 1.21.1, since only a few lines of code were changed between those versions.

As mentioned, you should use a dependency override to patch mods that expect Minecraft 1.21, rather than ask every other mod author to needlessly publish a separate version of their mod.
