### ISSUE TITLE
UI for changing config options

### ISSUE THREAD

**Issue by Mhowser** [jellysquid3/Lithium#7]
Would you be able to make a UI for the Lithium config file?

**Comment by silversquirl** [comment]
A UI would require a client-side component, but a command would probably be doable, like how carpet works

**Comment by Mhowser** [comment]
is the config file located at `.minecraft/config/lithium.json` server-side only?

**Comment by silversquirl** [comment]
Lithium is a server-side mod, so yes

**Comment by jellysquid3** [comment]
I'm not currently happy with how the configuration file is set up as JSON is a relatively poor choice and the comments are hidden in javadoc elsewhere. I'm going to be looking into replacing it with something better (perhaps TOML?) but the main concern remains keeping file size small.

As for implementing a client-side GUI... I'm not sure it'd have much use. Lithium's default configuration is designed to give you safe defaults and should be good for 99.9% of users. For the 0.1% that need something more, one would imagine that they would be comfortable editing text files. Otherwise, people just won't be touching it.

The other issue is that Lithium decides what patches to apply *before* the game finishes loading. It's not currently possible to enable or disable patches dynamically, and as such the client GUI would require a restart for every change. This could be changed, but it would make the code a bit more complex for not much added benefit (in my opinion.)

That said, I might be missing something here and my opinions don't necessarily represent those of everyone else. I'd love to hear the use case for something like this.

**Comment by Mhowser** [comment]
Everything that you said makes total sense, I thought Lithium had some clients side components based on what I read in the discord server. Thanks for the detailed explanation!
