### ISSUE TITLE
Game Crashes when loading world.

### ISSUE THREAD

**Issue by BDog102** [jellysquid3/Lithium#70]
When I have Optifabric and the new Optifine Prerelease installed the game does not crash but when I add lithium as well it crashes the world on startup.
[crash-2020-07-03_14.21.00-server.txt](https://github.com/jellysquid3/lithium-fabric/files/4871219/crash-2020-07-03_14.21.00-server.txt)

**Comment by amnotbananaama** [comment]
It sounds like this is an issue on OptiFabric/OptiFine's end. OptiFine is not intended to work on Fabric, and sp614x has explicitly said that he won't support Fabric. 

OptiFabric attempts to remap the Fabric .jar in order to be compatible with OptiFine. Sometimes this is not done perfectly (especially with lambdas) and this can lead to issues such as this. See https://github.com/modmuss50/OptiFabric/issues/112 for relevant information.

**Comment by 2No2Name** [comment]
Lithium uses access wideners to access that field. It might be that optifabric is breaking that. Can you try without optifabric?
